### ISSUE TITLE
Detect frozen tab environments and drop support for crosstab when detected.

### ISSUE THREAD

**Issue by tejacques** [tejacques/crosstab#1]
Currently frozen tab environments, where only the active tab is executing javascript, are detected using the user-agent. There is no feature or group of features than can be used to cover all scenarios, so in order to detect this, we'll have to get inventive.

Change crosstab from an object to a function, which takes an object / function that will be executed once crosstab setup is complete.

When a tab comes up, check if localStorage `crosstab.frozenTabEnvironment` is set to true. If it is, crosstab is not supported.

Otherwise check the user-agent against known frozen tab devices. If there is a match, set localStorage `crosstab.frozenTabEnvironment` and set crosstab to not supported.

Otherwise check if there is another tab registered as master. If there is attempt to PING the master. If we do not hear back within a short timeout (<50ms), then set localStorage `crosstab.frozenTabEnvironment` to true. When we hear back from the master, we will fire the `crosstab.setupComplete` event.

Otherwise register as normal, and fire the `crosstab.setupComplete` event, but check `crosstab.frozenTabEnvironment` when updating. If it is set, disable support.

Anywhere in code where you want to use crosstab, you should always check something in the style of:

``` JavaScript
function crosstabSupported() {
  // code here will execute once crosstab setup is complete if crosstab is supported.
}

function crosstabUnsupported() {
  // code here will execute once crosstab setup is complete if crosstab is unsupported
}

if (window.crosstab) {
  crosstab(function() {
    if (crosstab.supported) {
      crosstabSupported();
    } else {
      crosstabUnsupported();
    }
  });
} else {
  crosstabUnsupported();
}
```

This method will fail if the master tab is currently under enough load where 50ms is not sufficient to respond to a PING, however this should never practically occur. The one-time 50ms penalty for nondetected frozen tab environments should not be prohibitive

**Comment by kucheruk** [comment]
sometimes got FROZEN_TAB = true on Google Chrome v. 42.0.2311.135 (Windows 2008 R2)
