### ISSUE TITLE
Opening a number of tabs at once can result in no Master

### ISSUE THREAD

**Issue by moity** [tejacques/crosstab#28]
Repro:
1. Open a number of tabs (~5) with the supplied sample page `crosstab/samples/index.html`
2. Using IE(10) right-click one of the tabs and select "Refresh All" from the context menu

You may need to do this a few times to see the behaviour, but I usually get it within a few tries.  Once in this mode of no Master performing subsequent "Refresh All"s does not fix the problem.  One of the tabs appears to think it is Master (but is not reflecting that state) as refreshing the individual pages one by one eventually fixes the issue (on a specific tab).

While this may not be a typical user scenario I have seen it in production when a number of pages load at once (automatic logon after re-authentication).  

I've also noticed that under heavy load (JS intensive pages) localStorage can become a bit flaky with the timing of events, causing similar issues with the election process (this is a bit hard to show repro steps for).

**Comment by tejacques** [comment]
Does this only happen in IE / IE10? Or can you reproduce it in other browsers?

**Comment by moity** [comment]
IE10 is the only browser I've managed to consistently reproduce the issue with.  

In FF I see different behaviour, if I have 4 tabs open and perform a "Reload All" it thinks there are 8 tabs (and there is no master), until the 4 old tabs timeout, then a new master is elected and all is good.    

Chrome doesn't have a "Refresh All" method so I can't test that, but I am seeing strange behaviour too.  Such as multiple tabs becoming master when the previous master tab navigates or is refreshed, and occasionally there is no master.

A year or more ago I wrote something similar to what you have and found these same issues to prevail.  Working with a lightweight sample all seems to go quite well but once integrated into a real application problems with timing of events start to arise.  My first theory was that localStorage was flaky so I changed to using Cookies as the message bus (just to test the theory), this also worked well with lightweight pages but not under load.

I'm not sure what the solution is, some sort of outer timer doing a sweep for these erroneous conditions, issuing demotions when multiple masters exist, and promotion if none exists?

**Comment by tejacques** [comment]
It's very odd that there would be no master in an unrecoverable state, as all the tabs should be polling to check that there is a master and that no old tabs are present. I'll try to replicate this soon, maybe tomorrow. Thanks for bringing it up.

The behavior you're describing with FireFox happens because it isn't sending a pageunload event to the open tabs, so they don't have a chance to cleanup properly, but it's expected that none of the new ones will be master until the polling cycle completes and there's a new master election. I'll also look into that.

**Comment by tejacques** [comment]
Currently unable to replicate this.
