### ISSUE TITLE
Writing "null" to LocalStorage causes a "Cannot read property 'id' of null" error to be thrown

### ISSUE THREAD

**Issue by andrewwakeling** [tejacques/crosstab#40]
In onStorageEvent, it is optimistically parsing values as JSON and then assuming that the result is an object. This causes "eventValue" to be "null" and then "eventValue.id" to fail.

There are different ways of solving this, but I would have thought that crosstab should be checking the "key" property of all incoming StorageEvents and only processing ones that are relevant to crosstab.

Is using:
````javascript
if (event.key.indexOf('crosstab') !== 0) return;
````
a possible fix?

**Comment by tejacques** [comment]
This is a great catch. I think checking the key is the right way to go, but it's probably a little more robust to do something like this:

```.js
// setup
util.storageEventKeys = {};
util.forEach(util.keys, function(key) {
    util.storageEventKeys[key] = 1;
});
```
```.js
// check
if (!event.key in util.storageEventKeys) {
    // Not a crosstab event
    return;
}
```
