### ISSUE TITLE
Chrome & IE now broken?

### ISSUE THREAD

**Issue by gsc89** [tejacques/crosstab#68]
I have a very basic implementation of this using on 1 page: 

`
            crosstab.on('issue-a-item', function(data) {
                console.log('Called Crosstab');
                $('#barcode-search').val(data.data.barcode);
                lookupItem(true);
            });`

on another page:
`
        $('body').on('click', '.issue-this-item', function(e){
            e.preventDefault();
            var tr = $(this).closest('tr');
            var row = window.LaravelDataTables.dataTableBuilder.row(tr);
            var data = row.data();
            crosstab.broadcast('issue-a-item', { 'barcode' : data.barcode });
            setTimeout(function(){
                window.close();
            },500);
        });`

Still works on firefox but on chrome and IE (IE broke last year) it now gives me the Frozen Tab error on clicking "issue-this-item". 

Is there any alternatives to crosstab because I need this to work and I see from another issue you have said that you don't have the motivation to work on this.

**Comment by tejacques** [comment]
You got a timeout at some point and crosstab is caching the timeout to fast-fail. As a temporary measure you can clear your localstorage. There isn't really a working alternative to this project, as the reason I stopped working on this was IE/Edge have issues preventing 100% a correctly working solution.

It looks like there is some progress being made there however so I may start working on this again.

**Comment by gsc89** [comment]
Actually I have switched to this. https://github.com/MarkehMe/TabTalk

Much smaller plugin etc but no more issues on Chrome, IE or Firefox, you have to do a little more work like sending an object with the event name your calling but seems to work without issues.
