### ISSUE TITLE
Browser Tabs?

### ISSUE THREAD

**Issue by FunkMonkey33** [tejacques/crosstab#72]
Unless I'm missing something, crosstab doesn't actually open/enable communication between browser tabs.  Is that right?

The sample seems to only add a Div to the same tab you're on.  I was hoping for an effective way to coordinate two different browser tabs, one spawned by another calling window.open().

I'm going to play with it some more, as maybe the sample doesn't illustrate this functionality even if it does exist.

**Comment by tejacques** [comment]
It does, those divs are in iframes, which are effectively different tabs, it will work equivalently on a desktop browser.
